spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  #
#
#  #  jpa:
##    generate-ddl: true
#  jpa:
#    hibernate:
#      ddl-auto: none
  sql:
    init:
      mode: always
      platform: postgres